version: "3.7"
services:
  jupyter:
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    links:
      - postgres
      - mongo
    volumes:
          - "./notebooks:/notebooks" 
          - "./data:/data"

  mongo:
    image: mongo:3.2.11
    volumes:
      - /data/db/mongo
    ports:
      - "27017:27017"
  postgres:
    image: postgres:9.6.18
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        PGDATA: /data/db/postgres
